# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LambdaCurry 
email: http://scr.im/lambdacurry  
description: > # this means to ignore newlines until "baseurl:"
  Tech. Product. Enterpreneurship
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lambdacurry.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sandGorgon1 
github_username:  sandys
paginate:            15
paginate_path: '/posts/:num'
show_downloads: false
permalink: /:year/:month/:slug/ 
repository: sandys/lambdacurry.github.io 
# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-tactile
#theme: jekyll-theme-modernist

pages: ./_pages

disqus:
  shortname: lambdacurry

gems:
  - jekyll-feed
  - jekyll-gist 
exclude:
  - Gemfile
  - Gemfile.lock
